spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_store_management?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242